### ISSUE TITLE
引入选座组件到我的项目的时候 在移动端显示大小出现问题 请问改哪里

### ISSUE THREAD

**Issue by Goinsist** [zenghao0219/SeatSelect#1]
大小不能随屏幕自适应

**Comment by zenghao0219** [comment]
你好~首先这个项目布局是基于rem布局按照设计图宽度为750px编写的 
具体可以查看在postcss.config.js 中 引入的 postcss-px2rem 第三方控件配置 remUnit: 75 
因为座位图上方还有导航栏和座位图示例,所以座位图的高度是自适应的具体代码在 HallSeat.vue文件 307行
seatAreaHeightRem这个方法,是获取了(屏幕的可视高度-其他头部组件座位图示例,下方确认组件等等的高度自动计算的),这个应该是你需要改的地方,由于你的布局可能跟demo不一致 所以,只需要把减去的部分修改即可,还有欢迎加群一起讨论 群号: 3544395
